<?php

namespace app\models;

use yii\db\ActiveRecord;
use Yii;
use yii\web\IdentityInterface;

/**
 * Users model
 *
 * @property integer $id
 * @property string $nick
 * @property string $ip
 * @property string $city
 *
 */
class User extends ActiveRecord implements IdentityInterface
{
    /**
     * @return string
     */
    public static function tableName()
    {
        return 'users';
    }

    /**
     * @return array
     */
    public function rules()
    {
        return [
            ['nick', 'required']
        ];
    }

    public function attributeLabels()
    {
        return [
            'id'   => 'Id',
            'nick' => 'Nick',
            'ip'   => 'Ip',
            'city' => 'City'
        ];
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getNick()
    {
        return $this->nick;
    }

    /**
     * @return string
     */
    public function getIp()
    {
        return $this->ip;
    }

    public static function findIdentity($id) {
        return static::findOne($id);
    }

    public static function instantiate($row) {
        return new static($row);
    }

    /**
     * @param $nick
     * @return array|null|ActiveRecord|User
     */
    public static function findUserByNick($nick)
    {
        return self::find()
            ->where(['nick' => $nick])
            ->one()
        ;
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        return false;
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return '';
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return true;
    }

    public static function getAllUsers()
    {
        return self::find()
            ->all()
        ;
    }

    public function beforeSave($insert)
    {
        $this->ip = Yii::$app->request->getUserIP();
        $geoIp = Yii::$app->geoip->ip();
        $this->city = $geoIp->city;
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
